name: Update badges

on:
  # Only execute when needed
  workflow_dispatch:

jobs:
  update-readme:
    name: Update Readme with badges
    runs-on: ubuntu-latest
    steps:
      - name: Badges - Readme
        uses: pemtajo/badge-readme@main
        with:       
          CREDLY_USER: arvind-singh-rawat
          CREDLY_SORT: POPULAR
